data<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors=F)
datafeb<-subset(data,Date=="1/2/2007"|Date=="2/2/2007")
datafeb$Date<-as.Date(datafeb$Date,"%d/%m/%Y")
datafeb$datetime<-paste(datafeb$Date,datafeb$Time)
datafeb$timeplot<-as.POSIXct(datafeb$datetime)
Sys.setlocale("LC_TIME", "English")
plot(datafeb$Sub_metering_1~datafeb$timeplot, type="l", ylab="Energy sub metering", xlab="")
lines(datafeb$Sub_metering_2~datafeb$timeplot,col="red")
lines(datafeb$Sub_metering_3~datafeb$timeplot,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png",width=400,height=400)
dev.off()