data<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors=F)
datafeb<-subset(data,Date=="1/2/2007"|Date=="2/2/2007")
datafeb$Date<-as.Date(datafeb$Date,"%d/%m/%Y")
datafeb$datetime<-paste(datafeb$Date,datafeb$Time)
datafeb$timeplot<-as.POSIXct(datafeb$datetime)
Sys.setlocale("LC_TIME", "English")
datafeb$Global_active_power<-as.numeric(datafeb$Global_active_power)
par(mfrow = c(2, 2), mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(datafeb$Global_active_power~datafeb$timeplot, type="l", ylab="Global Active Power", xlab="")
plot(datafeb$Voltage~datafeb$timeplot, type="l", ylab="Voltage", xlab="datetime")
plot(datafeb$Sub_metering_1~datafeb$timeplot, type="l", ylab="Energy sub metering", xlab="")
lines(datafeb$Sub_metering_2~datafeb$timeplot,col="red")
lines(datafeb$Sub_metering_3~datafeb$timeplot,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.65)
plot(datafeb$Global_reactive_power~datafeb$timeplot, type="l",ylab="Global_reactive_power", xlab="datetime")
dev.copy(png,file="plot4.png",width=400,height=400)
dev.off()