data<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors=F)
datafeb<-subset(data,Date=="1/2/2007"|Date=="2/2/2007")
datafeb$Global_active_power<-as.numeric(datafeb$Global_active_power)
datafeb$Date<-as.Date(datafeb$Date,"%d/%m/%Y")
datafeb$datetime<-paste(datafeb$Date,datafeb$Time)
datafeb$timeplot<-as.POSIXct(datafeb$datetime)
Sys.setlocale("LC_TIME", "English")
plot(datafeb$Global_active_power~datafeb$timeplot, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png,file="plot2.png",width=400,height=400)
dev.off()